package todo.exception;

public class UserNotFoundException extends Exception {

}
